name: Build wheels (intermediate)

on:
  workflow_dispatch:

jobs:

  wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-13, macOS-latest, ubuntu-latest]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Build wheels
      uses: pypa/cibuildwheel@190455139953dd8820b39f9eaf4390ed11320d90 # v2.11.1
      env:
        CIBW_BUILD: cp39-* cp310-* cp311-* cp312-*
        CIBW_SKIP: "*-win32 *-manylinux_i686 pp* *-musllinux*"
    - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
      with:
        path: ./wheelhouse/*.whl
